version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.3
  clojure: lambdaisland/clojure@0.0.7

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - clojure/with_cache:
          cache_version: << parameters.clojure_version >>
          steps:
            - run: clojure -e '(println (System/getProperty "java.runtime.name") (System/getProperty "java.runtime.version") "\nClojure" (clojure-version))'
            - run: npm install ws
            - run: ./bin/kaocha

jobs:
  java-11-clojure-1_10:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.10.3"}}]

workflows:
  kaocha_test:
    jobs:
      - java-11-clojure-1_10
